Repository didx-xyz/yoma, pull requests merged in 2024-08, with the labels that each got.

#997 🩹 Large Client Header Buffers
  helm/keycloak/values.yaml
  helm/yoma-api/values.yaml
Labels: chore

#1002 Pull Large Headers config into Yoma API
  helm/yoma-api/conf/dev/values.yaml
  helm/yoma-api/conf/prod/values.yaml
  helm/yoma-api/conf/stage/values.yaml
Labels: chore

#1020 Fix Keycloak Config
  helm/yoma-api/conf/base/secrets.yaml
  helm/yoma-api/conf/dev/secrets.yaml
  helm/yoma-api/conf/prod/secrets.yaml
  helm/yoma-api/conf/stage/secrets.yaml
Labels: bug

#1021 Bump Datadog Lib Init
  helm/keycloak/values.yaml
  helm/yoma-api/values.yaml
  helm/yoma-web/values.yaml
Labels: chore

#1029 [YOMA-308, YOMA-467] SA Youth & ZLTO Item Reservation Timeout
  helm/yoma-api/conf/base/secrets.yaml
  src/api/src/application/Yoma.Core.Api/Startup.cs
  src/api/src/application/Yoma.Core.Api/appsettings.json
  src/api/src/domain/Yoma.Core.Domain/Core/Converters/IsoDateFormatConverter.cs
  src/api/src/domain/Yoma.Core.Domain/Core/Enumerations.cs
  src/api/src/domain/Yoma.Core.Domain/Core/Extensions/FlurlExtensions.cs
  src/api/src/domain/Yoma.Core.Domain/Core/Models/AppSettings.cs
  src/api/src/domain/Yoma.Core.Domain/Entity/Extensions/OrganizationExtensions.cs
  src/api/src/domain/Yoma.Core.Domain/Entity/Services/UserProfileService.cs
  src/api/src/domain/Yoma.Core.Domain/Entity/Validators/UserRequestValidator.cs
  src/api/src/domain/Yoma.Core.Domain/Lookups/Helpers/TimeIntervalHelper.cs
  src/api/src/domain/Yoma.Core.Domain/Marketplace/Services/MarketPlaceService.cs
  src/api/src/domain/Yoma.Core.Domain/Opportunity/Extensions/OpportunityExtensions.cs
  src/api/src/domain/Yoma.Core.Domain/Opportunity/Models/Opportunity.cs
  src/api/src/domain/Yoma.Core.Domain/Opportunity/Models/OpportunityInfo.cs
  src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityBackgroundService.cs
  src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityInfoService.cs
  src/api/src/domain/Yoma.Core.Domain/Opportunity/Services/OpportunityService.cs
  src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Interfaces/IProcessingLogHelperService.cs
  src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Interfaces/ISharingInfoService.cs
  src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Models/OppotunityRequestUpsert.cs
  src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/Lookups/PartnerService.cs
  src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/ProcessingLogHelperService .cs
  src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/SharingBackgroundService.cs
  src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/SharingInfoService.cs
  src/api/src/domain/Yoma.Core.Domain/PartnerSharing/Services/SharingService.cs
  src/api/src/domain/Yoma.Core.Domain/Reward/Services/RewardService.cs
  src/api/src/domain/Yoma.Core.Domain/Reward/Services/WalletService.cs
  src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSICredentialService.cs
  src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSISchemaService.cs
  src/api/src/domain/Yoma.Core.Domain/SSI/Services/SSITenantService.cs
  src/api/src/domain/Yoma.Core.Domain/Startup.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Opportunity/Repositories/OpportunityRepository.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Client/SAYouthClient.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Extensions/OpportunityExtensions.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Extensions/ResponseExtensions.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Models/Address.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Models/Contact.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Models/Enumerations.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Models/OpportunityActionRequest.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.SAYouth/Models/OpportunitySkillingUpsertRequest.cs
Labels: on hold

#1039 Resolve Docker Build warnings
  helm/yoma-api/conf/stage/values.yaml
  src/web/Dockerfile
Labels: chore

#1040 Revert removal of required docker variables
  src/web/Dockerfile
Labels: bug

#1053 Yoma API HPA, PDB, Pre-Stop, better health probes
  .github/workflows/cicd.yml
  helm/keycloak/Chart.lock
  helm/keycloak/Chart.yaml
  helm/keycloak/values.yaml
  helm/yoma-api/Chart.lock
  helm/yoma-api/Chart.yaml
  helm/yoma-api/conf/prod/values.yaml
  helm/yoma-api/conf/stage/values.yaml
  helm/yoma-api/templates/_helpers.tpl
  helm/yoma-api/templates/deployment.yaml
  helm/yoma-api/templates/hpa.yaml
  helm/yoma-api/templates/ingress.yaml
  helm/yoma-api/templates/pdb.yaml
  helm/yoma-api/templates/post-install.yaml
  helm/yoma-api/templates/pvc.yaml
  helm/yoma-api/templates/secret.yaml
  helm/yoma-api/templates/service.yaml
  helm/yoma-api/templates/serviceaccount.yaml
  helm/yoma-api/values.yaml
Labels: api, infra

#1057 Fix Husky Install Deprecated warning
  package.json
Labels: chore
