Repository didx-xyz/yoma, pull requests merged in 2024-04, with the labels that each got.

#672 Disable HTTPS Redirect
  helm/yoma-api/conf/base/secrets.yaml
Labels: chore, api

#673 Correctly disable Sentry Debug in Stage/Prod
  helm/yoma-api/conf/prod/secrets.yaml
  helm/yoma-api/conf/stage/secrets.yaml
Labels: chore, api

#682 [YOMA-16] Fix missing `Should deploy` check for `release`
  .github/workflows/cicd.yml
Labels: bug

#686 Don't use `sha` docker tag if Release
  .github/workflows/cicd.yml
Labels: bug

#708 Empty `wwwroot`
  src/api/Dockerfile
Labels: chore, api

#709 Datadog JS APM injection in Yoma Web
  helm/yoma-api/Chart.yaml
  helm/yoma-api/values.yaml
  helm/yoma-web/Chart.yaml
  helm/yoma-web/templates/deployment.yaml
  helm/yoma-web/values.yaml
  helmfile.yaml
Labels: enhancement, web

#715 Set up basic and detailed health checks at /api/v3/health/ready and /api/v3/health/live
  helm/yoma-api/templates/deployment.yaml
  src/api/src/application/Yoma.Core.Api/Startup.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Startup.cs
  src/api/src/infrastructure/Yoma.Core.Infrastructure.Database/Yoma.Core.Infrastructure.Database.csproj
Labels: enhancement, api

#746 Fix Keycloak SMTP Sender
  src/keycloak/exports/01-yoma-realm.yaml
Labels: bug

#748 Scope Deploy Concurrency by Environment
  .github/workflows/cicd.yml
Labels: chore

#751 Increase Nginx Proxy Buffer for Yoma Web Ingresses
  helm/yoma-web/conf/dev/values.yaml
  helm/yoma-web/conf/prod/values.yaml
  helm/yoma-web/conf/stage/values.yaml
Labels: bug

#756 Hotfix: Fix Deploy Concurrency Group
  .github/workflows/cicd.yml
Labels: bug
